#!/usr/bin/python3
"""THis module contains a lots of function
and more functions
and more functions
"""


def add(a, b):
    """
    this function takes two int as argument and returns their sum
    """
    return a+b


def sub(a, b):
    """
    this function takes two int as argument and returns their difference
    """
    return a-b


def div(a, b):
    """
    this function takes two int as argument and returns their division
    """
    return int(a/b)


def mult(a, b):
    """
    this function takes two int as argument and returns their multiplication
    """
    return a*b


def pow(a, b):
    """
    this function takes two int as argument and returns their difference
    """
    return a ** b


def islower(c):
    """
    this function takes a character and returns True it is lowercase else False
    """
    if 97 <= ord(c) <= 122:
        return True
    else:
        return False


def search_replace(my_list, search, replace):
    """
    this function takes the 'search' in a list and replace with 'replace'
    """
    new_list = my_list[:]
    for i in range(len(new_list)):
        if new_list[i] == search:
            new_list[i] = replace
    return new_list


def uniq_add(my_list=[]):
    """this function takes all the element that exist more than once,
    regard each of them as one, and all element of the list
    """
    my_list = set(my_list.copy())
    my_list = list(my_list)
    sum = 0
    for i in range(len(my_list)):
        sum += my_list[i]
    return sum


def number_keys(a_dictionary):
    """
    this function return all the keys of a dictionary
    """
    i = 0
    for keys in a_dictionary:
        i = i + 1
    return i


def uppercase(str):
    """This function change the string passed to uppercase either
    uppercase is passed as argument or the other way round
    """
    strr = list(str)
    for i in range(len(str)):
        if (ord(str[i]) >= 95) and (ord(str[i]) <= 122):
            strr[i] = chr(ord(str[i]) - 32)
    str = "".join(strr)
    print("{}".format(str))
